cd C:\Users\matti\Desktop\Thesis\Data\Stata

use data_frame_abadie_v2.dta, clear
keep if date ==684
drop if erreur1 == 1
keep if Framed == 1 | supercontrole == 1
gen age2 = age^2
tabulate region, generate(dregion)

estrat_mult ouverture1 Duration, potential(epuise_bis) pred(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) control(supercontrole) cov(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) loo_only boot(1000)

estrat_mult ouverture1 Duration, potential(epuise_bis) pred(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) control(supercontrole) cov(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) rss_only

keep if PBD >= 730

estrat_mult ouverture1 Duration, potential(epuise_bis) pred(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) control(supercontrole) cov(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) boot(1000) loo_only

estrat_mult ouverture1 Duration, potential(epuise_bis) pred(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) control(supercontrole) cov(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) rss_only


use data_frame_abadie_v2.dta, clear
keep if date ==684
drop if erreur1 == 1

keep if Framed == 1 |controle == 1
gen age2 = age^2
tabulate region, generate(dregion)


estrat_mult ouverture1 Duration, potential(epuise_bis) pred(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) control(controle) cov(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) loo_only boot(1000)

estrat_mult ouverture1 Duration, potential(epuise_bis) pred(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) control(controle) cov(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) rss_only


keep if PBD >= 730

estrat_mult ouverture1 Duration, potential(epuise_bis) pred(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) control(controle) cov(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) loo_only boot(1000)

estrat_mult ouverture1 Duration, potential(epuise_bis) pred(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) control(controle) cov(femme age age2 upper_2nd_edu higher_edu contrat_moins_12mois contrat_moins_3mois episode_rac_numero episode_rac_numero_mois indemnisation PBD SJR married foreigner tx_chge tx_chge_jeunes proportion_de_ar proportion_de_ld proportion_de_sortants nombre_de nombre_de_rct divorced primaire secondaire cdi lic  dregion2  dregion3  dregion4  dregion5  dregion6  dregion7  dregion8  dregion9  dregion10  dregion11  dregion12  dregion13  dregion14  dregion15  dregion16  dregion17  dregion18  dregion19  dregion20  dregion21  dregion22  dregion23  dregion24  dregion25  dregion26  dregion27  dregion28) rss_only

translate @Results proba_epuise_final_730.txt